module.exports = [
      "Absorb and Release",
      "Acid",
      "Air Propulsion",
      "All for One",
      "Animal Voice",
      "Attraction of Small Objects",
      "Autotomy",
      "Beast",
      "Black",
      "Black Hole",
      "Blood Manipulation",
      "Bloodcurdle",
      "Bonespear",
      "Brainwashing",
      "Cemedine",
      "Cement",
      "Clones",
      "Compression",
      "Copy",
      "Creation",
      "Cremation",
      "Dark Shadow",
      "Dental Manipulation",
      "Disintegration",
      "Dupli-Atms",
      "Earphone Jack",
      "Earth Flow",
      "Electrification",
      "Engine",
      "Erasure",
      "Explosion",
      "Fiber Master",
      "Fire Breath",
      "Foldabody",
      "Forceible Quirk Activation",
      "Four Arms",
      "Frog-Form",
      "Gatling",
      "Gigantification",
      "Half Cold Half Hot",
      "Hardening",
      "Hell Flame",
      "High Spec",
      "Hydrokinesis",
      "Homing",
      "Horn Cannon",
      "Hypertrophy",
      "Impact Recoil",
      "Infrared Ray",
      "Jet",
      "Large Fists",
      "Liquid Cloning (Double)",
      "Longevity",
      "Lumber",
      "Magnetism",
      "Manuel's Quirk (Unnamed)",
      "Muscle Augmentation",
      "Muscle Enlargment",
      "Musculoskeletal Coiling",
      "Mushroom",
      "Navel Laser",
      "One For All",
      "Paralyzation",
      "Poltergeist",
      "Pop Off",
      "Proliferation",
      "Pterodactyl",
      "Recovery",
      "Scales",
      "Search",
      "Sharp Blade",
      "Shock Absorption",
      "Size",
      "Sleep Gas",
      "Snake Hair",
      "Softness",
      "Solid Air",
      "Somnambulist",
      "Sugar Rush",
      "Super Regeneration",
      "Swiveling",
      "Rivet",
      "Tail",
      "Tape",
      "Telepath",
      "Tongue Web",
      "Tool Arms",
      "Transmission",
      "Transform",
      "Transparency",
      "Twin Impact",
      "Vines",
      "Voice",
      "Warp Gate",
      "Water Creation",
      "Zero Gravity",
      "Zoom"
    ];